import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface ReportEmailRequest {
  to: string;
  reportTitle: string;
  htmlContent: string;
  assetSymbol?: string;
}

const handler = async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { to, reportTitle, htmlContent, assetSymbol }: ReportEmailRequest = await req.json();

    console.log("📧 Sending report email to:", to);

    const emailResponse = await resend.emails.send({
      from: "Alphalens Reports <onboarding@resend.dev>",
      to: [to],
      subject: assetSymbol 
        ? `${reportTitle} - ${assetSymbol}`
        : reportTitle,
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>${reportTitle}</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f5f5f5;
              }
              .email-container {
                background-color: white;
                border-radius: 8px;
                padding: 30px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
              }
              .header {
                border-bottom: 3px solid #2563eb;
                padding-bottom: 15px;
                margin-bottom: 25px;
              }
              .header h1 {
                margin: 0;
                color: #1e40af;
                font-size: 24px;
              }
              .content {
                margin-top: 20px;
              }
              .footer {
                margin-top: 40px;
                padding-top: 20px;
                border-top: 1px solid #e5e7eb;
                font-size: 12px;
                color: #6b7280;
                text-align: center;
              }
            </style>
          </head>
          <body>
            <div class="email-container">
              <div class="header">
                <h1>${reportTitle}</h1>
                ${assetSymbol ? `<p style="color: #6b7280; margin: 5px 0 0 0;">Target Asset: ${assetSymbol}</p>` : ''}
              </div>
              <div class="content">
                ${htmlContent}
              </div>
              <div class="footer">
                <p>This report was generated by Alphalens Research Platform</p>
                <p>© ${new Date().getFullYear()} Alphalens. All rights reserved.</p>
              </div>
            </div>
          </body>
        </html>
      `,
    });

    console.log("✅ Report email sent successfully:", emailResponse);

    return new Response(JSON.stringify({ 
      success: true,
      messageId: emailResponse.id 
    }), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders,
      },
    });
  } catch (error: any) {
    console.error("❌ Error sending report email:", error);
    return new Response(
      JSON.stringify({ 
        success: false,
        error: error.message 
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);
