INSERT INTO blog_posts (slug,title,content,excerpt,author,category,language,meta_title,meta_description,status,tags,published_at)
SELECT s.slug, s.title, s.content, s.excerpt, s.author, s.category, 'en', s.meta_title, s.meta_description, 'published', s.tags, s.published_at::timestamptz
FROM (VALUES
('how-ai-generates-trading-signals','How AI Generates Trading Signals: From Data to Actionable Setups','Placeholder - will be updated','A guide to AI trading signal generation','AlphaLens Research','research','How AI Generates Trading Signals | AlphaLens AI','Learn how AI generates trading signals with practical frameworks.','published',ARRAY['ai','trading signals','machine learning'],'2025-04-07T12:54:00+00:00'),
('momentum-vs-mean-reversion-ai','Momentum vs Mean Reversion: How AI Selects the Right Strategy','Placeholder','Guide to AI strategy selection','AlphaLens Research','research','Momentum vs Mean Reversion AI | AlphaLens AI','How AI selects between momentum and mean reversion strategies.','published',ARRAY['momentum','mean reversion','strategy'],'2025-04-10T21:33:00+00:00'),
('multi-timeframe-signal-analysis','Multi-Timeframe Signal Analysis with AI: A Practical Approach','Placeholder','Multi-timeframe AI analysis guide','AlphaLens Research','research','Multi-Timeframe Signal Analysis AI | AlphaLens AI','Learn multi-timeframe signal analysis with AI frameworks.','published',ARRAY['timeframes','signals','technical analysis'],'2025-04-14T06:12:00+00:00'),
('ai-entry-exit-timing','AI for Trade Entry and Exit Timing: What the Data Shows','Placeholder','AI trade timing guide','AlphaLens Research','research','AI Trade Entry Exit Timing | AlphaLens AI','Learn AI trade entry and exit timing with data-driven insights.','published',ARRAY['entry','exit','timing','data'],'2025-04-17T14:51:00+00:00'),
('risk-reward-optimization-ai','Risk-Reward Optimization with AI: Beyond Simple Ratios','Placeholder','Risk-reward AI optimization guide','AlphaLens Research','research','Risk-Reward Optimization AI | AlphaLens AI','Learn risk-reward optimization with AI beyond simple ratios.','published',ARRAY['risk','reward','optimization'],'2025-04-20T23:30:00+00:00')
) AS s(slug,title,content,excerpt,author,category,meta_title,meta_description,status,tags,published_at)
WHERE NOT EXISTS (SELECT 1 FROM blog_posts bp WHERE bp.slug = s.slug);